In [1]:
import pandas as pd
import itertools
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set() 
%matplotlib inline
import codecs
import os
from src import all_run_data
from src import make_d_list
from src import Open_save_file
from src import make_send_csv


#Register data for transmission

with codecs.open(r"./data/send_simulation_data.csv", "r", "Shift-JIS", "ignore") as file:
        send_simulation_data = pd.read_table(file, delimiter=",")

sent_data = send_simulation_data

#Please include the pass for the master data below

master_data_path = r"./data/masuta_simulation_data.csv"

#Create the save folder after the analysis below.

savefolder = r'./output/'
save_date = "2022_07_make_simulation_data"


if not os.path.exists(savefolder+save_date):
    os.mkdir(savefolder+save_date)  
Export_folder = savefolder[0:]+save_date

In [2]:
all_run_data.all_run_spd(sent_data,master_data_path,Export_folder)

[('1月1日', 'A_1'),
 ('4月24日', 'A_1'),
 ('10月24日', 'A_1'),
 ('2月15日', 'A_1'),
 ('8月17日', 'A_1'),
 ('12月9日', 'A_1'),
 ('6月9日', 'A_1'),
 ('10月1日', 'A_1'),
 ('4月2日', 'A_1'),
 ('7月25日', 'A_1'),
 ('1月24日', 'A_1'),
 ('5月17日', 'A_1'),
 ('11月16日', 'A_1'),
 ('3月10日', 'A_1'),
 ('9月9日', 'A_1')]
df_r_all       Date Department_Item  index  claim  Department_code_  Department_  \
0    10月1日             A_1      1      1                 1            1
1   10月24日             A_1      1      1                 1            1
2   11月16日             A_1      1      1                 1            1
3    12月9日             A_1      1      1                 1            1
4     1月1日             A_1      2      2                 2            2
5    1月24日             A_1      1      1                 1            1
6    2月15日             A_1      1      1                 1            1
7    3月10日             A_1      1      1                 1            1
8    4月24日             A_1      1      1                 1            1
9     4月2日             A_1      1      1                 1            1
10   5月17日             A_1      1      1                 1            1
11    6月9日             A_1      1      1                 1            1
12   7月25日             A_1      1      1                 1            1
13   8月17日             A_1      1      1                 1            1
14    9月9日             A_1      1      1                 1            1

    item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0             1       1              1            1           1         1
1             1       1              1            1           1         1
2             1       1              1            1           1         1
3             1       1              1            1           1         1
4             2       2              2            2           2         2
5             1       1              1            1           1         1
6             1       1              1            1           1         1
7             1       1              1            1           1         1
8             1       1              1            1           1         1
9             1       1              1            1           1         1
10            1       1              1            1           1         1
11            1       1              1            1           1         1
12            1       1              1            1           1         1
13            1       1              1            1           1         1
14            1       1              1            1           1         1
0
A
[('1月1日', 'A_1'),
 ('4月24日', 'A_1'),
 ('10月24日', 'A_1'),
 ('2月15日', 'A_1'),
 ('8月17日', 'A_1'),
 ('12月9日', 'A_1'),
 ('6月9日', 'A_1'),
 ('10月1日', 'A_1'),
 ('4月2日', 'A_1'),
 ('7月25日', 'A_1'),
 ('1月24日', 'A_1'),
 ('5月17日', 'A_1'),
 ('11月16日', 'A_1'),
 ('3月10日', 'A_1'),
 ('9月9日', 'A_1')]
df_r_all       Date Department_Item  index  claim  Department_code_  Department_  \
0    10月1日             A_1      1      1                 1            1
1   10月24日             A_1      1      1                 1            1
2   11月16日             A_1      1      1                 1            1
3    12月9日             A_1      1      1                 1            1
4     1月1日             A_1      2      2                 2            2
5    1月24日             A_1      1      1                 1            1
6    2月15日             A_1      1      1                 1            1
7    3月10日             A_1      1      1                 1            1
8    4月24日             A_1      1      1                 1            1
9     4月2日             A_1      1      1                 1            1
10   5月17日             A_1      1      1                 1            1
11    6月9日             A_1      1      1                 1            1
12   7月25日             A_1      1      1                 1            1
13   8月17日             A_1      1      1                 1            1
14    9月9日             A_1      1      1                 1            1

    item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0             1       1              1            1           1         1
1             1       1              1            1           1         1
2             1       1              1            1           1         1
3             1       1              1            1           1         1
4             2       2              2            2           2         2
5             1       1              1            1           1         1
6             1       1              1            1           1         1
7             1       1              1            1           1         1
8             1       1              1            1           1         1
9             1       1              1            1           1         1
10            1       1              1            1           1         1
11            1       1              1            1           1         1
12            1       1              1            1           1         1
13            1       1              1            1           1         1
14            1       1              1            1           1         1
1
B
[('1月2日', 'B_2'),
 ('1月2日', 'B_1'),
 ('10月25日', 'B_2'),
 ('10月25日', 'B_1'),
 ('8月18日', 'B_2'),
 ('8月18日', 'B_1'),
 ('6月10日', 'B_2'),
 ('6月10日', 'B_1'),
 ('4月3日', 'B_2'),
 ('4月3日', 'B_1'),
 ('1月25日', 'B_2'),
 ('1月25日', 'B_1'),
 ('11月17日', 'B_2'),
 ('11月17日', 'B_1'),
 ('9月10日', 'B_2'),
 ('9月10日', 'B_1'),
 ('2月9日', 'B_2'),
 ('2月9日', 'B_1'),
 ('4月25日', 'B_2'),
 ('4月25日', 'B_1'),
 ('12月2日', 'B_2'),
 ('12月2日', 'B_1'),
 ('2月16日', 'B_2'),
 ('2月16日', 'B_1'),
 ('9月25日', 'B_2'),
 ('9月25日', 'B_1'),
 ('12月10日', 'B_2'),
 ('12月10日', 'B_1'),
 ('7月18日', 'B_2'),
 ('7月18日', 'B_1'),
 ('10月2日', 'B_2'),
 ('10月2日', 'B_1'),
 ('5月11日', 'B_2'),
 ('5月11日', 'B_1'),
 ('7月26日', 'B_2'),
 ('7月26日', 'B_1'),
 ('3月3日', 'B_2'),
 ('3月3日', 'B_1'),
 ('5月18日', 'B_2'),
 ('5月18日', 'B_1'),
 ('12月25日', 'B_2'),
 ('12月25日', 'B_1'),
 ('3月11日', 'B_2'),
 ('3月11日', 'B_1'),
 ('10月18日', 'B_2'),
 ('10月18日', 'B_1')]
df_r_all       Date Department_Item  index  claim  Department_code_  Department_  \
0   10月18日             B_1      1      1                 1            1
1   10月25日             B_2      1      1                 1            1
2    10月2日             B_1      1      1                 1            1
3   11月17日             B_2      1      1                 1            1
4   12月10日             B_1      1      1                 1            1
5   12月25日             B_1      1      1                 1            1
6    12月2日             B_1      1      1                 1            1
7    1月25日             B_2      1      1                 1            1
8     1月2日             B_1      1      1                 1            1
9     1月2日             B_2      1      1                 1            1
10   2月16日             B_1      1      1                 1            1
11    2月9日             B_1      1      1                 1            1
12   3月11日             B_1      1      1                 1            1
13    3月3日             B_1      1      1                 1            1
14   4月25日             B_1      1      1                 1            1
15    4月3日             B_2      1      1                 1            1
16   5月11日             B_1      1      1                 1            1
17   5月18日             B_1      1      1                 1            1
18   6月10日             B_2      1      1                 1            1
19   7月18日             B_1      1      1                 1            1
20   7月26日             B_1      1      1                 1            1
21   8月18日             B_2      1      1                 1            1
22   9月10日             B_2      1      1                 1            1
23   9月25日             B_1      1      1                 1            1

    item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0             1       1              1            1           1         1
1             1       1              1            1           1         1
2             1       1              1            1           1         1
3             1       1              1            1           1         1
4             1       1              1            1           1         1
5             1       1              1            1           1         1
6             1       1              1            1           1         1
7             1       1              1            1           1         1
8             1       1              1            1           1         1
9             1       1              1            1           1         1
10            1       1              1            1           1         1
11            1       1              1            1           1         1
12            1       1              1            1           1         1
13            1       1              1            1           1         1
14            1       1              1            1           1         1
15            1       1              1            1           1         1
16            1       1              1            1           1         1
17            1       1              1            1           1         1
18            1       1              1            1           1         1
19            1       1              1            1           1         1
20            1       1              1            1           1         1
21            1       1              1            1           1         1
22            1       1              1            1           1         1
23            1       1              1            1           1         1
2
C
[('1月3日', 'C_3'),
 ('1月3日', 'C_2'),
 ('10月26日', 'C_3'),
 ('10月26日', 'C_2'),
 ('8月19日', 'C_3'),
 ('8月19日', 'C_2'),
 ('6月11日', 'C_3'),
 ('6月11日', 'C_2'),
 ('4月4日', 'C_3'),
 ('4月4日', 'C_2'),
 ('1月26日', 'C_3'),
 ('1月26日', 'C_2'),
 ('11月18日', 'C_3'),
 ('11月18日', 'C_2'),
 ('9月11日', 'C_3'),
 ('9月11日', 'C_2'),
 ('2月10日', 'C_3'),
 ('2月10日', 'C_2'),
 ('4月26日', 'C_3'),
 ('4月26日', 'C_2'),
 ('12月3日', 'C_3'),
 ('12月3日', 'C_2'),
 ('2月17日', 'C_3'),
 ('2月17日', 'C_2'),
 ('9月26日', 'C_3'),

 ('9月26日', 'C_2'),
 ('12月11日', 'C_3'),
 ('12月11日', 'C_2'),
 ('7月19日', 'C_3'),
 ('7月19日', 'C_2'),
 ('10月3日', 'C_3'),
 ('10月3日', 'C_2'),
 ('5月12日', 'C_3'),
 ('5月12日', 'C_2'),
 ('7月27日', 'C_3'),
 ('7月27日', 'C_2'),
 ('3月4日', 'C_3'),
 ('3月4日', 'C_2'),
 ('5月19日', 'C_3'),
 ('5月19日', 'C_2'),
 ('12月26日', 'C_3'),
 ('12月26日', 'C_2'),
 ('3月12日', 'C_3'),
 ('3月12日', 'C_2'),
 ('10月19日', 'C_3'),
 ('10月19日', 'C_2')]
df_r_all       Date Department_Item  index  claim  Department_code_  Department_  \
0   10月19日             C_2      1      1                 1            1
1   10月26日             C_3      1      1                 1            1
2    10月3日             C_2      1      1                 1            1
3   11月18日             C_3      1      1                 1            1
4   12月11日             C_2      1      1                 1            1
5   12月26日             C_2      1      1                 1            1
6    12月3日             C_2      1      1                 1            1
7    1月26日             C_3      1      1                 1            1
8     1月3日             C_2      1      1                 1            1
9     1月3日             C_3      1      1                 1            1
10   2月10日             C_2      1      1                 1            1
11   2月17日             C_2      1      1                 1            1
12   3月12日             C_2      1      1                 1            1
13    3月4日             C_2      1      1                 1            1
14   4月26日             C_2      1      1                 1            1
15    4月4日             C_3      1      1                 1            1
16   5月12日             C_2      1      1                 1            1
17   5月19日             C_2      1      1                 1            1
18   6月11日             C_3      1      1                 1            1
19   7月19日             C_2      1      1                 1            1
20   7月27日             C_2      1      1                 1            1
21   8月19日             C_3      1      1                 1            1
22   9月11日             C_3      1      1                 1            1
23   9月26日             C_2      1      1                 1            1

    item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0             1       1              1            1           1         1
1             1       1              1            1           1         1
2             1       1              1            1           1         1
3             1       1              1            1           1         1
4             1       1              1            1           1         1
5             1       1              1            1           1         1
6             1       1              1            1           1         1
7             1       1              1            1           1         1
8             1       1              1            1           1         1
9             1       1              1            1           1         1
10            1       1              1            1           1         1
11            1       1              1            1           1         1
12            1       1              1            1           1         1
13            1       1              1            1           1         1
14            1       1              1            1           1         1
15            1       1              1            1           1         1
16            1       1              1            1           1         1
17            1       1              1            1           1         1
18            1       1              1            1           1         1
19            1       1              1            1           1         1
20            1       1              1            1           1         1
21            1       1              1            1           1         1
22            1       1              1            1           1         1
23            1       1              1            1           1         1
3
D
[('2月11日', 'D_3'),
 ('4月27日', 'D_3'),
 ('12月4日', 'D_3'),
 ('2月18日', 'D_3'),
 ('9月27日', 'D_3'),
 ('12月12日', 'D_3'),
 ('7月20日', 'D_3'),
 ('10月4日', 'D_3'),
 ('5月13日', 'D_3'),
 ('7月28日', 'D_3'),
 ('3月5日', 'D_3'),
 ('5月20日', 'D_3'),
 ('12月27日', 'D_3'),
 ('3月13日', 'D_3'),
 ('10月20日', 'D_3'),
 ('1月4日', 'D_3')]
df_r_all       Date Department_Item  index  claim  Department_code_  Department_  \
0   10月20日             D_3      1      1                 1            1
1    10月4日             D_3      1      1                 1            1
2   12月12日             D_3      1      1                 1            1
3   12月27日             D_3      1      1                 1            1
4    12月4日             D_3      1      1                 1            1
5     1月4日             D_3      1      1                 1            1
6    2月11日             D_3      1      1                 1            1
7    2月18日             D_3      1      1                 1            1
8    3月13日             D_3      1      1                 1            1
9     3月5日             D_3      1      1                 1            1
10   4月27日             D_3      1      1                 1            1
11   5月13日             D_3      1      1                 1            1
12   5月20日             D_3      1      1                 1            1
13   7月20日             D_3      1      1                 1            1
14   7月28日             D_3      1      1                 1            1
15   9月27日             D_3      1      1                 1            1

    item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0             1       1              1            1           1         1
1             1       1              1            1           1         1
2             1       1              1            1           1         1
3             1       1              1            1           1         1
4             1       1              1            1           1         1
5             1       1              1            1           1         1
6             1       1              1            1           1         1
7             1       1              1            1           1         1
8             1       1              1            1           1         1
9             1       1              1            1           1         1
10            1       1              1            1           1         1
11            1       1              1            1           1         1
12            1       1              1            1           1         1
13            1       1              1            1           1         1
14            1       1              1            1           1         1
15            1       1              1            1           1         1
4
E
[('4月28日', 'E_4'),
 ('2月19日', 'E_4'),
 ('12月13日', 'E_4'),
 ('10月5日', 'E_4'),
 ('7月29日', 'E_4'),
 ('5月21日', 'E_4'),
 ('3月14日', 'E_4'),
 ('1月5日', 'E_4')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0   10月5日             E_4      1      1                 1            1
1  12月13日             E_4      1      1                 1            1
2    1月5日             E_4      1      1                 1            1
3   2月19日             E_4      1      1                 1            1
4   3月14日             E_4      1      1                 1            1
5   4月28日             E_4      1      1                 1            1
6   5月21日             E_4      1      1                 1            1
7   7月29日             E_4      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
5
F

[('4月29日', 'F_5'),
 ('2月20日', 'F_5'),
 ('12月14日', 'F_5'),
 ('10月6日', 'F_5'),
 ('7月30日', 'F_5'),
 ('5月22日', 'F_5'),
 ('3月15日', 'F_5'),
 ('1月6日', 'F_5')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0   10月6日             F_5      1      1                 1            1
1  12月14日             F_5      1      1                 1            1
2    1月6日             F_5      1      1                 1            1
3   2月20日             F_5      1      1                 1            1
4   3月15日             F_5      1      1                 1            1
5   4月29日             F_5      1      1                 1            1
6   5月22日             F_5      1      1                 1            1
7   7月30日             F_5      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
6
G
[('4月30日', 'G_6'),
 ('2月21日', 'G_6'),
 ('12月15日', 'G_6'),
 ('10月7日', 'G_6'),
 ('7月31日', 'G_6'),
 ('5月23日', 'G_6'),
 ('3月16日', 'G_6'),
 ('1月7日', 'G_6')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0   10月7日             G_6      1      1                 1            1
1  12月15日             G_6      1      1                 1            1
2    1月7日             G_6      1      1                 1            1
3   2月21日             G_6      1      1                 1            1
4   3月16日             G_6      1      1                 1            1
5   4月30日             G_6      1      1                 1            1
6   5月23日             G_6      1      1                 1            1
7   7月31日             G_6      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
7
H
[('5月1日', 'H_7'),
 ('2月22日', 'H_7'),
 ('12月16日', 'H_7'),
 ('10月8日', 'H_7'),
 ('8月1日', 'H_7'),
 ('5月24日', 'H_7'),
 ('3月17日', 'H_7'),
 ('1月8日', 'H_7')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0   10月8日             H_7      1      1                 1            1
1  12月16日             H_7      1      1                 1            1
2    1月8日             H_7      1      1                 1            1
3   2月22日             H_7      1      1                 1            1
4   3月17日             H_7      1      1                 1            1
5    5月1日             H_7      1      1                 1            1
6   5月24日             H_7      1      1                 1            1
7    8月1日             H_7      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
8
I
[('5月2日', 'I_8'),
 ('2月23日', 'I_8'),
 ('12月17日', 'I_8'),
 ('10月9日', 'I_8'),
 ('8月2日', 'I_8'),
 ('5月25日', 'I_8'),
 ('3月18日', 'I_8'),
 ('1月9日', 'I_8')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0   10月9日             I_8      1      1                 1            1
1  12月17日             I_8      1      1                 1            1
2    1月9日             I_8      1      1                 1            1
3   2月23日             I_8      1      1                 1            1
4   3月18日             I_8      1      1                 1            1
5   5月25日             I_8      1      1                 1            1
6    5月2日             I_8      1      1                 1            1
7    8月2日             I_8      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
9
J
[('5月3日', 'J_9'),
 ('2月24日', 'J_9'),
 ('12月18日', 'J_9'),
 ('10月10日', 'J_9'),
 ('8月3日', 'J_9'),
 ('5月26日', 'J_9'),
 ('3月19日', 'J_9'),
 ('1月10日', 'J_9')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月10日             J_9      1      1                 1            1
1  12月18日             J_9      1      1                 1            1
2   1月10日             J_9      1      1                 1            1
3   2月24日             J_9      1      1                 1            1
4   3月19日             J_9      1      1                 1            1
5   5月26日             J_9      1      1                 1            1
6    5月3日             J_9      1      1                 1            1
7    8月3日             J_9      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
10
K
[('5月4日', 'K_10'),
 ('2月25日', 'K_10'),
 ('12月19日', 'K_10'),
 ('10月11日', 'K_10'),
 ('8月4日', 'K_10'),
 ('5月27日', 'K_10'),
 ('3月20日', 'K_10'),
 ('1月11日', 'K_10')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月11日            K_10      1      1                 1            1
1  12月19日            K_10      1      1                 1            1
2   1月11日            K_10      1      1                 1            1
3   2月25日            K_10      1      1                 1            1
4   3月20日            K_10      1      1                 1            1
5   5月27日            K_10      1      1                 1            1
6    5月4日            K_10      1      1                 1            1
7    8月4日            K_10      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
11
L
[('5月5日', 'L_11'),
 ('2月26日', 'L_11'),
 ('12月20日', 'L_11'),
 ('10月12日', 'L_11'),
 ('8月5日', 'L_11'),
 ('5月28日', 'L_11'),
 ('3月21日', 'L_11'),
 ('1月12日', 'L_11')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月12日            L_11      1      1                 1            1
1  12月20日            L_11      1      1                 1            1
2   1月12日            L_11      1      1                 1            1
3   2月26日            L_11      1      1                 1            1
4   3月21日            L_11      1      1                 1            1
5   5月28日            L_11      1      1                 1            1
6    5月5日            L_11      1      1                 1            1
7    8月5日            L_11      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1

12
M
[('5月6日', 'M_12'),
 ('2月27日', 'M_12'),
 ('12月21日', 'M_12'),
 ('10月13日', 'M_12'),
 ('8月6日', 'M_12'),
 ('5月29日', 'M_12'),
 ('3月22日', 'M_12'),
 ('1月13日', 'M_12')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月13日            M_12      1      1                 1            1
1  12月21日            M_12      1      1                 1            1
2   1月13日            M_12      1      1                 1            1
3   2月27日            M_12      1      1                 1            1
4   3月22日            M_12      1      1                 1            1
5   5月29日            M_12      1      1                 1            1
6    5月6日            M_12      1      1                 1            1
7    8月6日            M_12      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
13
N
[('5月7日', 'N_13'),
 ('2月28日', 'N_13'),
 ('12月22日', 'N_13'),
 ('10月14日', 'N_13'),
 ('8月7日', 'N_13'),
 ('5月30日', 'N_13'),
 ('3月23日', 'N_13'),
 ('1月14日', 'N_13')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月14日            N_13      1      1                 1            1
1  12月22日            N_13      1      1                 1            1
2   1月14日            N_13      1      1                 1            1
3   2月28日            N_13      1      1                 1            1
4   3月23日            N_13      1      1                 1            1
5   5月30日            N_13      1      1                 1            1
6    5月7日            N_13      1      1                 1            1
7    8月7日            N_13      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
14
O
[('5月8日', 'O_14'),
 ('3月1日', 'O_14'),
 ('12月23日', 'O_14'),
 ('10月15日', 'O_14'),
 ('8月8日', 'O_14'),
 ('5月31日', 'O_14'),
 ('3月24日', 'O_14'),
 ('1月15日', 'O_14')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月15日            O_14      1      1                 1            1
1  12月23日            O_14      1      1                 1            1
2   1月15日            O_14      1      1                 1            1
3    3月1日            O_14      1      1                 1            1
4   3月24日            O_14      1      1                 1            1
5   5月31日            O_14      1      1                 1            1
6    5月8日            O_14      1      1                 1            1
7    8月8日            O_14      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
15
P
[('5月9日', 'P_15'),
 ('3月2日', 'P_15'),
 ('12月24日', 'P_15'),
 ('10月16日', 'P_15'),
 ('8月9日', 'P_15'),
 ('6月1日', 'P_15'),
 ('3月25日', 'P_15'),
 ('1月16日', 'P_15')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月16日            P_15      1      1                 1            1
1  12月24日            P_15      1      1                 1            1
2   1月16日            P_15      1      1                 1            1
3   3月25日            P_15      1      1                 1            1
4    3月2日            P_15      1      1                 1            1
5    5月9日            P_15      1      1                 1            1
6    6月1日            P_15      1      1                 1            1
7    8月9日            P_15      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
16
Q
[('5月10日', 'Q_16'),
 ('3月3日', 'Q_16'),
 ('12月25日', 'Q_16'),
 ('10月17日', 'Q_16'),
 ('8月10日', 'Q_16'),
 ('6月2日', 'Q_16'),
 ('3月26日', 'Q_16'),
 ('1月17日', 'Q_16')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月17日            Q_16      1      1                 1            1
1  12月25日            Q_16      1      1                 1            1
2   1月17日            Q_16      1      1                 1            1
3   3月26日            Q_16      1      1                 1            1
4    3月3日            Q_16      1      1                 1            1
5   5月10日            Q_16      1      1                 1            1
6    6月2日            Q_16      1      1                 1            1
7   8月10日            Q_16      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
17
R
[('5月11日', 'R_17'),
 ('3月4日', 'R_17'),
 ('12月26日', 'R_17'),
 ('10月18日', 'R_17'),
 ('8月11日', 'R_17'),
 ('6月3日', 'R_17'),
 ('3月27日', 'R_17'),
 ('1月18日', 'R_17')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月18日            R_17      1      1                 1            1
1  12月26日            R_17      1      1                 1            1
2   1月18日            R_17      1      1                 1            1
3   3月27日            R_17      1      1                 1            1
4    3月4日            R_17      1      1                 1            1
5   5月11日            R_17      1      1                 1            1
6    6月3日            R_17      1      1                 1            1
7   8月11日            R_17      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
18
S
[('5月12日', 'S_18'),
 ('3月5日', 'S_18'),
 ('12月27日', 'S_18'),
 ('10月19日', 'S_18'),
 ('8月12日', 'S_18'),
 ('6月4日', 'S_18'),
 ('3月28日', 'S_18'),
 ('1月19日', 'S_18')]

df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月19日            S_18      1      1                 1            1
1  12月27日            S_18      1      1                 1            1
2   1月19日            S_18      1      1                 1            1
3   3月28日            S_18      1      1                 1            1
4    3月5日            S_18      1      1                 1            1
5   5月12日            S_18      1      1                 1            1
6    6月4日            S_18      1      1                 1            1
7   8月12日            S_18      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
19
T
[('5月13日', 'T_19'),
 ('3月6日', 'T_19'),
 ('12月28日', 'T_19'),
 ('10月20日', 'T_19'),
 ('8月13日', 'T_19'),
 ('6月5日', 'T_19'),
 ('3月29日', 'T_19'),
 ('1月20日', 'T_19')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月20日            T_19      1      1                 1            1
1  12月28日            T_19      1      1                 1            1
2   1月20日            T_19      1      1                 1            1
3   3月29日            T_19      1      1                 1            1
4    3月6日            T_19      1      1                 1            1
5   5月13日            T_19      1      1                 1            1
6    6月5日            T_19      1      1                 1            1
7   8月13日            T_19      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
20
U
[('5月14日', 'U_20'),
 ('3月7日', 'U_20'),
 ('12月29日', 'U_20'),
 ('10月21日', 'U_20'),
 ('8月14日', 'U_20'),
 ('6月6日', 'U_20'),
 ('3月30日', 'U_20'),
 ('1月21日', 'U_20')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月21日            U_20      1      1                 1            1
1  12月29日            U_20      1      1                 1            1
2   1月21日            U_20      1      1                 1            1
3   3月30日            U_20      1      1                 1            1
4    3月7日            U_20      1      1                 1            1
5   5月14日            U_20      1      1                 1            1
6    6月6日            U_20      1      1                 1            1
7   8月14日            U_20      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
21
V
[('5月15日', 'V_21'),
 ('3月8日', 'V_21'),
 ('12月30日', 'V_21'),
 ('10月22日', 'V_21'),
 ('8月15日', 'V_21'),
 ('6月7日', 'V_21'),
 ('3月31日', 'V_21'),
 ('1月22日', 'V_21')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月22日            V_21      1      1                 1            1
1  12月30日            V_21      1      1                 1            1
2   1月22日            V_21      1      1                 1            1
3   3月31日            V_21      1      1                 1            1
4    3月8日            V_21      1      1                 1            1
5   5月15日            V_21      1      1                 1            1
6    6月7日            V_21      1      1                 1            1
7   8月15日            V_21      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
22
W
[('5月16日', 'W_22'),
 ('3月9日', 'W_22'),
 ('12月31日', 'W_22'),
 ('10月23日', 'W_22'),
 ('8月16日', 'W_22'),
 ('6月8日', 'W_22'),
 ('4月1日', 'W_22'),
 ('1月23日', 'W_22')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月23日            W_22      1      1                 1            1
1  12月31日            W_22      1      1                 1            1
2   1月23日            W_22      1      1                 1            1
3    3月9日            W_22      1      1                 1            1
4    4月1日            W_22      1      1                 1            1
5   5月16日            W_22      1      1                 1            1
6    6月8日            W_22      1      1                 1            1
7   8月16日            W_22      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
23
X
[('5月17日', 'X_23'),
 ('3月10日', 'X_23'),
 ('1月1日', 'X_23'),
 ('10月24日', 'X_23'),
 ('8月17日', 'X_23'),
 ('6月9日', 'X_23'),
 ('4月2日', 'X_23'),
 ('1月24日', 'X_23')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月24日            X_23      1      1                 1            1
1    1月1日            X_23      1      1                 1            1
2   1月24日            X_23      1      1                 1            1
3   3月10日            X_23      1      1                 1            1
4    4月2日            X_23      1      1                 1            1
5   5月17日            X_23      1      1                 1            1
6    6月9日            X_23      1      1                 1            1
7   8月17日            X_23      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
24
Y
[('5月18日', 'Y_24'),
 ('3月11日', 'Y_24'),
 ('1月2日', 'Y_24'),
 ('10月25日', 'Y_24'),
 ('8月18日', 'Y_24'),
 ('6月10日', 'Y_24'),
 ('4月3日', 'Y_24'),
 ('1月25日', 'Y_24')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月25日            Y_24      1      1                 1            1
1   1月25日            Y_24      1      1                 1            1
2    1月2日            Y_24      1      1                 1            1
3   3月11日            Y_24      1      1                 1            1
4    4月3日            Y_24      1      1                 1            1
5   5月18日            Y_24      1      1                 1            1
6   6月10日            Y_24      1      1                 1            1
7   8月18日            Y_24      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
25
Z
[('5月19日', 'Z_25'),
 ('3月12日', 'Z_25'),
 ('1月3日', 'Z_25'),
 ('10月26日', 'Z_25'),
 ('8月19日', 'Z_25'),
 ('6月11日', 'Z_25'),
 ('4月4日', 'Z_25'),
 ('1月26日', 'Z_25')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月26日            Z_25      1      1                 1            1
1   1月26日            Z_25      1      1                 1            1
2    1月3日            Z_25      1      1                 1            1
3   3月12日            Z_25      1      1                 1            1
4    4月4日            Z_25      1      1                 1            1
5   5月19日            Z_25      1      1                 1            1
6   6月11日            Z_25      1      1                 1            1
7   8月19日            Z_25      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1

26
AA
[('5月20日', 'AA_26'),
 ('3月13日', 'AA_26'),
 ('1月4日', 'AA_26'),
 ('10月27日', 'AA_26'),
 ('8月20日', 'AA_26'),
 ('6月12日', 'AA_26'),
 ('4月5日', 'AA_26'),
 ('1月27日', 'AA_26')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月27日           AA_26      1      1                 1            1
1   1月27日           AA_26      1      1                 1            1
2    1月4日           AA_26      1      1                 1            1
3   3月13日           AA_26      1      1                 1            1
4    4月5日           AA_26      1      1                 1            1
5   5月20日           AA_26      1      1                 1            1
6   6月12日           AA_26      1      1                 1            1
7   8月20日           AA_26      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
27
AB
[('5月21日', 'AB_27'),
 ('3月14日', 'AB_27'),
 ('1月5日', 'AB_27'),
 ('10月28日', 'AB_27'),
 ('8月21日', 'AB_27'),
 ('6月13日', 'AB_27'),
 ('4月6日', 'AB_27'),
 ('1月28日', 'AB_27')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月28日           AB_27      1      1                 1            1
1   1月28日           AB_27      1      1                 1            1
2    1月5日           AB_27      1      1                 1            1
3   3月14日           AB_27      1      1                 1            1
4    4月6日           AB_27      1      1                 1            1
5   5月21日           AB_27      1      1                 1            1
6   6月13日           AB_27      1      1                 1            1
7   8月21日           AB_27      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
28
AC
[('5月22日', 'AC_28'),
 ('3月15日', 'AC_28'),
 ('1月6日', 'AC_28'),
 ('10月29日', 'AC_28'),
 ('8月22日', 'AC_28'),
 ('6月14日', 'AC_28'),
 ('4月7日', 'AC_28'),
 ('1月29日', 'AC_28')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月29日           AC_28      1      1                 1            1
1   1月29日           AC_28      1      1                 1            1
2    1月6日           AC_28      1      1                 1            1
3   3月15日           AC_28      1      1                 1            1
4    4月7日           AC_28      1      1                 1            1
5   5月22日           AC_28      1      1                 1            1
6   6月14日           AC_28      1      1                 1            1
7   8月22日           AC_28      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
29
AD
[('5月23日', 'AD_29'),
 ('3月16日', 'AD_29'),
 ('1月7日', 'AD_29'),
 ('10月30日', 'AD_29'),
 ('8月23日', 'AD_29'),
 ('6月15日', 'AD_29'),
 ('4月8日', 'AD_29'),
 ('1月30日', 'AD_29')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月30日           AD_29      1      1                 1            1
1   1月30日           AD_29      1      1                 1            1
2    1月7日           AD_29      1      1                 1            1
3   3月16日           AD_29      1      1                 1            1
4    4月8日           AD_29      1      1                 1            1
5   5月23日           AD_29      1      1                 1            1
6   6月15日           AD_29      1      1                 1            1
7   8月23日           AD_29      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
30
AE
[('5月24日', 'AE_30'),
 ('3月17日', 'AE_30'),
 ('1月8日', 'AE_30'),
 ('10月31日', 'AE_30'),
 ('8月24日', 'AE_30'),
 ('6月16日', 'AE_30'),
 ('4月9日', 'AE_30'),
 ('1月31日', 'AE_30')]
df_r_all      Date Department_Item  index  claim  Department_code_  Department_  \
0  10月31日           AE_30      1      1                 1            1
1   1月31日           AE_30      1      1                 1            1
2    1月8日           AE_30      1      1                 1            1
3   3月17日           AE_30      1      1                 1            1
4    4月9日           AE_30      1      1                 1            1
5   5月24日           AE_30      1      1                 1            1
6   6月16日           AE_30      1      1                 1            1
7   8月24日           AE_30      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
31
AF
[('5月25日', 'AF_31'),
 ('3月18日', 'AF_31'),
 ('1月9日', 'AF_31'),
 ('11月1日', 'AF_31'),
 ('8月25日', 'AF_31'),
 ('6月17日', 'AF_31'),
 ('4月10日', 'AF_31'),
 ('2月1日', 'AF_31')]
df_r_all     Date Department_Item  index  claim  Department_code_  Department_  \
0  11月1日           AF_31      1      1                 1            1
1   1月9日           AF_31      1      1                 1            1
2   2月1日           AF_31      1      1                 1            1
3  3月18日           AF_31      1      1                 1            1
4  4月10日           AF_31      1      1                 1            1
5  5月25日           AF_31      1      1                 1            1
6  6月17日           AF_31      1      1                 1            1
7  8月25日           AF_31      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
32
AG
[('5月26日', 'AG_32'),
 ('3月19日', 'AG_32'),
 ('1月10日', 'AG_32'),
 ('11月2日', 'AG_32'),
 ('8月26日', 'AG_32'),
 ('6月18日', 'AG_32'),
 ('4月11日', 'AG_32'),
 ('2月2日', 'AG_32')]
df_r_all     Date Department_Item  index  claim  Department_code_  Department_  \
0  11月2日           AG_32      1      1                 1            1
1  1月10日           AG_32      1      1                 1            1
2   2月2日           AG_32      1      1                 1            1
3  3月19日           AG_32      1      1                 1            1
4  4月11日           AG_32      1      1                 1            1
5  5月26日           AG_32      1      1                 1            1
6  6月18日           AG_32      1      1                 1            1
7  8月26日           AG_32      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1
33
AH
[('5月27日', 'AH_33'),
 ('3月20日', 'AH_33'),
 ('1月11日', 'AH_33'),
 ('11月3日', 'AH_33'),
 ('8月27日', 'AH_33'),
 ('6月19日', 'AH_33'),
 ('4月12日', 'AH_33'),
 ('2月3日', 'AH_33')]
df_r_all     Date Department_Item  index  claim  Department_code_  Department_  \
0  11月3日           AH_33      1      1                 1            1
1  1月11日           AH_33      1      1                 1            1
2   2月3日           AH_33      1      1                 1            1
3  3月20日           AH_33      1      1                 1            1
4  4月12日           AH_33      1      1                 1            1
5  5月27日           AH_33      1      1                 1            1
6  6月19日           AH_33      1      1                 1            1
7  8月27日           AH_33      1      1                 1            1

   item_code_x  Date_y  Department_CD  item_code_y  Department  standard
0            1       1              1            1           1         1
1            1       1              1            1           1         1
2            1       1              1            1           1         1
3            1       1              1            1           1         1
4            1       1              1            1           1         1
5            1       1              1            1           1         1
6            1       1              1            1           1         1
7            1       1              1            1           1         1

    Unnamed: 0    day1  count Department_Item use_signature
0            0    1月2日    1.0             B_2             B
1            1  10月25日    1.0             B_2             B
2            2   8月18日    1.0             B_2             B
3            3   6月10日    1.0             B_2             B
4            4    4月3日    1.0             B_2             B
..         ...     ...    ...             ...           ...
10          10   1月24日    1.0             A_1             A
11          11   5月17日    1.0             A_1             A
12          12  11月16日    1.0             A_1             A
13          13   3月10日    1.0             A_1             A
14          14    9月9日    1.0             A_1             A

[61 rows x 5 columns]